/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./.vitepress/theme/components/aboutMe.vue')['default']
    Archive: typeof import('./.vitepress/theme/components/Archive.vue')['default']
    ArticleCard: typeof import('./.vitepress/theme/components/articleCard.vue')['default']
    ArticleMetadata: typeof import('./.vitepress/theme/components/ArticleMetadata.vue')['default']
    Backtotop: typeof import('./.vitepress/theme/components/backtotop.vue')['default']
    BodyClick: typeof import('./.vitepress/theme/components/BodyClick.vue')['default']
    Comment: typeof import('./.vitepress/theme/components/layout/Comment.vue')['default']
    Copyright: typeof import('./.vitepress/theme/components/layout/Copyright.vue')['default']
    FeatureTag: typeof import('./.vitepress/theme/components/FeatureTag.vue')['default']
    Footer: typeof import('./.vitepress/theme/components/layout/Footer.vue')['default']
    Home: typeof import('./.vitepress/theme/components/home.vue')['default']
    ImageViewer: typeof import('./.vitepress/theme/components/imageViewer.vue')['default']
    LinkButton: typeof import('./.vitepress/theme/components/linkButton.vue')['default']
    LinkInline: typeof import('./.vitepress/theme/components/LinkInline.vue')['default']
    MNavLink: typeof import('./.vitepress/theme/components/MNavLink.vue')['default']
    MNavLinks: typeof import('./.vitepress/theme/components/MNavLinks.vue')['default']
    NavVisitor: typeof import('./.vitepress/theme/components/NavVisitor.vue')['default']
    Sakula: typeof import('./.vitepress/theme/components/Sakula.vue')['default']
    Tag: typeof import('./.vitepress/theme/components/Tag.vue')['default']
    TdesignDark: typeof import('./.vitepress/theme/components/tdesignDark.vue')['default']
    WordCloud: typeof import('./.vitepress/theme/components/WordCloud.vue')['default']
  }
}
