/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./.vitepress/theme/components/aboutMe.vue')['default']
    AButton: typeof import('@arco-design/web-vue')['Button']
    AButtonGroup: typeof import('@arco-design/web-vue')['ButtonGroup']
    ACard: typeof import('@arco-design/web-vue')['Card']
    ACol: typeof import('@arco-design/web-vue')['Col']
    AList: typeof import('@arco-design/web-vue')['List']
    AListItem: typeof import('@arco-design/web-vue')['ListItem']
    Archive: typeof import('./.vitepress/theme/components/Archive.vue')['default']
    ARow: typeof import('@arco-design/web-vue')['Row']
    ArticleCard: typeof import('./.vitepress/theme/components/articleCard.vue')['default']
    ArticleGPT: typeof import('./.vitepress/theme/components/ArticleGPT.vue')['default']
    ArticleMetadata: typeof import('./.vitepress/theme/components/ArticleMetadata.vue')['default']
    ATag: typeof import('@arco-design/web-vue')['Tag']
    Backtotop: typeof import('./.vitepress/theme/components/backtotop.vue')['default']
    BodyClick: typeof import('./.vitepress/theme/components/BodyClick.vue')['default']
    Comment: typeof import('./.vitepress/theme/components/layout/Comment.vue')['default']
    Copyright: typeof import('./.vitepress/theme/components/layout/Copyright.vue')['default']
    FeatureTag: typeof import('./.vitepress/theme/components/FeatureTag.vue')['default']
    Fireworks: typeof import('./.vitepress/theme/components/Fireworks.vue')['default']
    Footer: typeof import('./.vitepress/theme/components/layout/Footer.vue')['default']
    Heatmap: typeof import('./.vitepress/theme/components/heatmap.vue')['default']
    Home: typeof import('./.vitepress/theme/components/home.vue')['default']
    IconShareAlt: typeof import('@arco-design/web-vue/es/icon')['IconShareAlt']
    IconTrophy: typeof import('@arco-design/web-vue/es/icon')['IconTrophy']
    ImageViewer: typeof import('./.vitepress/theme/components/imageViewer.vue')['default']
    LinkButton: typeof import('./.vitepress/theme/components/linkButton.vue')['default']
    LinkInline: typeof import('./.vitepress/theme/components/LinkInline.vue')['default']
    MAsideSponsors: typeof import('./.vitepress/theme/components/MAsideSponsors.vue')['default']
    MNavLink: typeof import('./.vitepress/theme/components/MNavLink.vue')['default']
    MNavLinks: typeof import('./.vitepress/theme/components/MNavLinks.vue')['default']
    NavVisitor: typeof import('./.vitepress/theme/components/NavVisitor.vue')['default']
    ReloadPrompt: typeof import('./.vitepress/theme/components/ReloadPrompt.vue')['default']
    Sakula: typeof import('./.vitepress/theme/components/Sakula.vue')['default']
    Tag: typeof import('./.vitepress/theme/components/Tag.vue')['default']
    TdesignDark: typeof import('./.vitepress/theme/components/tdesignDark.vue')['default']
    TImageViewer: typeof import('tdesign-vue-next')['ImageViewer']
    Timeline: typeof import('./.vitepress/theme/components/Timeline.vue')['default']
    TPopup: typeof import('tdesign-vue-next')['Popup']
    ValineComment: typeof import('./.vitepress/theme/components/ValineComment.vue')['default']
    WordCloud: typeof import('./.vitepress/theme/components/WordCloud.vue')['default']
  }
}
